import { Aircraft } from './types';

export const aircraftDatabase: Aircraft[] = [
  // Turboprops
  {
    id: 'pilatus-pc12-ng',
    model: 'PC-12 NG',
    manufacturer: 'Pilatus',
    category: 'turboprop',
    passengerCapacity: { typical: 6, maximum: 9 },
    range: { nauticalMiles: 1803, kilometers: 3339 },
    cruiseSpeed: { knots: 280, kmh: 519 },
    fuelConsumption: { gallonsPerHour: 70, litersPerHour: 265 },
    emissionsFactor: { kgCO2PerKm: 1.2, kgCO2PerNauticalMile: 2.22 },
  },
  {
    id: 'cessna-grand-caravan-ex',
    model: 'Grand Caravan EX',
    manufacturer: 'Cessna',
    category: 'turboprop',
    passengerCapacity: { typical: 9, maximum: 14 },
    range: { nauticalMiles: 1070, kilometers: 1982 },
    cruiseSpeed: { knots: 185, kmh: 343 },
    fuelConsumption: { gallonsPerHour: 65, litersPerHour: 246 },
    emissionsFactor: { kgCO2PerKm: 1.1, kgCO2PerNauticalMile: 2.04 },
  },
  {
    id: 'beechcraft-king-air-350i',
    model: 'King Air 350/350i',
    manufacturer: 'Beechcraft',
    category: 'turboprop',
    passengerCapacity: { typical: 9, maximum: 11 },
    range: { nauticalMiles: 1806, kilometers: 3345 },
    cruiseSpeed: { knots: 312, kmh: 578 },
    fuelConsumption: { gallonsPerHour: 122, litersPerHour: 462 },
    emissionsFactor: { kgCO2PerKm: 1.5, kgCO2PerNauticalMile: 2.78 },
  },

  // Very Light Jets (VLJs)
  {
    id: 'cirrus-vision-jet-sf50',
    model: 'Vision Jet SF50',
    manufacturer: 'Cirrus',
    category: 'very-light',
    passengerCapacity: { typical: 5, maximum: 7 },
    range: { nauticalMiles: 1200, kilometers: 2222 },
    cruiseSpeed: { knots: 311, kmh: 576 },
    fuelConsumption: { gallonsPerHour: 55, litersPerHour: 208 },
    emissionsFactor: { kgCO2PerKm: 1.8, kgCO2PerNauticalMile: 3.33 },
  },
  {
    id: 'eclipse-550',
    model: 'Eclipse 550',
    manufacturer: 'Eclipse',
    category: 'very-light',
    passengerCapacity: { typical: 4, maximum: 6 },
    range: { nauticalMiles: 1125, kilometers: 2084 },
    cruiseSpeed: { knots: 375, kmh: 695 },
    fuelConsumption: { gallonsPerHour: 55, litersPerHour: 208 },
    emissionsFactor: { kgCO2PerKm: 1.9, kgCO2PerNauticalMile: 3.52 },
  },
  {
    id: 'hondajet-elite-ii',
    model: 'HondaJet Elite II',
    manufacturer: 'Honda',
    category: 'very-light',
    passengerCapacity: { typical: 5, maximum: 6 },
    range: { nauticalMiles: 1547, kilometers: 2865 },
    cruiseSpeed: { knots: 422, kmh: 782 },
    fuelConsumption: { gallonsPerHour: 92, litersPerHour: 348 },
    emissionsFactor: { kgCO2PerKm: 2.0, kgCO2PerNauticalMile: 3.70 },
  },
  {
    id: 'cessna-citation-mustang',
    model: 'Citation Mustang',
    manufacturer: 'Cessna',
    category: 'very-light',
    passengerCapacity: { typical: 4, maximum: 6 },
    range: { nauticalMiles: 1167, kilometers: 2161 },
    cruiseSpeed: { knots: 340, kmh: 630 },
    fuelConsumption: { gallonsPerHour: 100, litersPerHour: 379 },
    emissionsFactor: { kgCO2PerKm: 2.1, kgCO2PerNauticalMile: 3.89 },
  },
  {
    id: 'embraer-phenom-100ev',
    model: 'Phenom 100EV',
    manufacturer: 'Embraer',
    category: 'very-light',
    passengerCapacity: { typical: 4, maximum: 6 },
    range: { nauticalMiles: 1178, kilometers: 2182 },
    cruiseSpeed: { knots: 406, kmh: 752 },
    fuelConsumption: { gallonsPerHour: 110, litersPerHour: 416 },
    emissionsFactor: { kgCO2PerKm: 2.2, kgCO2PerNauticalMile: 4.07 },
  },

  // Light Jets
  {
    id: 'cessna-citation-cj1-plus',
    model: 'Citation CJ1/CJ1+',
    manufacturer: 'Cessna',
    category: 'light',
    passengerCapacity: { typical: 5, maximum: 6 },
    range: { nauticalMiles: 1300, kilometers: 2408 },
    cruiseSpeed: { knots: 389, kmh: 721 },
    fuelConsumption: { gallonsPerHour: 100, litersPerHour: 379 },
    emissionsFactor: { kgCO2PerKm: 2.1, kgCO2PerNauticalMile: 3.89 },
  },
  {
    id: 'cessna-citation-m2',
    model: 'Citation M2',
    manufacturer: 'Cessna',
    category: 'light',
    passengerCapacity: { typical: 5, maximum: 7 },
    range: { nauticalMiles: 1550, kilometers: 2871 },
    cruiseSpeed: { knots: 404, kmh: 748 },
    fuelConsumption: { gallonsPerHour: 110, litersPerHour: 416 },
    emissionsFactor: { kgCO2PerKm: 2.2, kgCO2PerNauticalMile: 4.07 },
  },
  {
    id: 'cessna-citation-cj3-plus',
    model: 'Citation CJ3+',
    manufacturer: 'Cessna',
    category: 'light',
    passengerCapacity: { typical: 6, maximum: 7 },
    range: { nauticalMiles: 2040, kilometers: 3778 },
    cruiseSpeed: { knots: 416, kmh: 770 },
    fuelConsumption: { gallonsPerHour: 160, litersPerHour: 606 },
    emissionsFactor: { kgCO2PerKm: 2.4, kgCO2PerNauticalMile: 4.44 },
  },
  {
    id: 'cessna-citation-cj4',
    model: 'Citation CJ4',
    manufacturer: 'Cessna',
    category: 'light',
    passengerCapacity: { typical: 7, maximum: 9 },
    range: { nauticalMiles: 2165, kilometers: 4010 },
    cruiseSpeed: { knots: 451, kmh: 835 },
    fuelConsumption: { gallonsPerHour: 161, litersPerHour: 609 },
    emissionsFactor: { kgCO2PerKm: 2.3, kgCO2PerNauticalMile: 4.26 },
  },
  {
    id: 'embraer-phenom-300e',
    model: 'Phenom 300/300E',
    manufacturer: 'Embraer',
    category: 'light',
    passengerCapacity: { typical: 6, maximum: 9 },
    range: { nauticalMiles: 2010, kilometers: 3724 },
    cruiseSpeed: { knots: 453, kmh: 839 },
    fuelConsumption: { gallonsPerHour: 170, litersPerHour: 644 },
    emissionsFactor: { kgCO2PerKm: 2.5, kgCO2PerNauticalMile: 4.63 },
  },
  {
    id: 'learjet-70-75-liberty',
    model: 'Learjet 70/75 Liberty',
    manufacturer: 'Bombardier',
    category: 'light',
    passengerCapacity: { typical: 6, maximum: 8 },
    range: { nauticalMiles: 2060, kilometers: 3815 },
    cruiseSpeed: { knots: 465, kmh: 861 },
    fuelConsumption: { gallonsPerHour: 220, litersPerHour: 833 },
    emissionsFactor: { kgCO2PerKm: 2.7, kgCO2PerNauticalMile: 5.00 },
  },
  {
    id: 'nextant-400xti',
    model: '400XTi',
    manufacturer: 'Nextant',
    category: 'light',
    passengerCapacity: { typical: 7, maximum: 8 },
    range: { nauticalMiles: 2003, kilometers: 3710 },
    cruiseSpeed: { knots: 460, kmh: 852 },
    fuelConsumption: { gallonsPerHour: 170, litersPerHour: 644 },
    emissionsFactor: { kgCO2PerKm: 2.3, kgCO2PerNauticalMile: 4.26 },
  },
  {
    id: 'beechcraft-hawker-400xp',
    model: 'Hawker 400XP',
    manufacturer: 'Beechcraft',
    category: 'light',
    passengerCapacity: { typical: 7, maximum: 9 },
    range: { nauticalMiles: 1480, kilometers: 2741 },
    cruiseSpeed: { knots: 450, kmh: 834 },
    fuelConsumption: { gallonsPerHour: 185, litersPerHour: 700 },
    emissionsFactor: { kgCO2PerKm: 2.5, kgCO2PerNauticalMile: 4.63 },
  },

  // Midsize Jets
  {
    id: 'cessna-citation-bravo',
    model: 'Citation Bravo',
    manufacturer: 'Cessna',
    category: 'midsize',
    passengerCapacity: { typical: 6, maximum: 8 },
    range: { nauticalMiles: 1920, kilometers: 3556 },
    cruiseSpeed: { knots: 420, kmh: 778 },
    fuelConsumption: { gallonsPerHour: 180, litersPerHour: 681 },
    emissionsFactor: { kgCO2PerKm: 2.5, kgCO2PerNauticalMile: 4.63 },
  },
  {
    id: 'cessna-citation-xls-plus',
    model: 'Citation XLS/XLS+',
    manufacturer: 'Cessna',
    category: 'midsize',
    passengerCapacity: { typical: 8, maximum: 9 },
    range: { nauticalMiles: 2100, kilometers: 3889 },
    cruiseSpeed: { knots: 441, kmh: 817 },
    fuelConsumption: { gallonsPerHour: 220, litersPerHour: 833 },
    emissionsFactor: { kgCO2PerKm: 2.7, kgCO2PerNauticalMile: 5.00 },
  },
  {
    id: 'cessna-citation-latitude',
    model: 'Citation Latitude',
    manufacturer: 'Cessna',
    category: 'midsize',
    passengerCapacity: { typical: 7, maximum: 9 },
    range: { nauticalMiles: 2700, kilometers: 5000 },
    cruiseSpeed: { knots: 446, kmh: 826 },
    fuelConsumption: { gallonsPerHour: 210, litersPerHour: 795 },
    emissionsFactor: { kgCO2PerKm: 2.6, kgCO2PerNauticalMile: 4.81 },
  },
  {
    id: 'hawker-850xp',
    model: 'Hawker 800XP/850XP/900XP',
    manufacturer: 'Beechcraft',
    category: 'midsize',
    passengerCapacity: { typical: 8, maximum: 9 },
    range: { nauticalMiles: 2540, kilometers: 4704 },
    cruiseSpeed: { knots: 447, kmh: 828 },
    fuelConsumption: { gallonsPerHour: 280, litersPerHour: 1060 },
    emissionsFactor: { kgCO2PerKm: 3.0, kgCO2PerNauticalMile: 5.56 },
  },
  {
    id: 'learjet-60xr',
    model: 'Learjet 60XR',
    manufacturer: 'Bombardier',
    category: 'midsize',
    passengerCapacity: { typical: 6, maximum: 8 },
    range: { nauticalMiles: 2405, kilometers: 4454 },
    cruiseSpeed: { knots: 457, kmh: 847 },
    fuelConsumption: { gallonsPerHour: 203, litersPerHour: 768 },
    emissionsFactor: { kgCO2PerKm: 2.5, kgCO2PerNauticalMile: 4.63 },
  },
  {
    id: 'embraer-legacy-450',
    model: 'Legacy 450',
    manufacturer: 'Embraer',
    category: 'midsize',
    passengerCapacity: { typical: 7, maximum: 9 },
    range: { nauticalMiles: 2904, kilometers: 5378 },
    cruiseSpeed: { knots: 464, kmh: 859 },
    fuelConsumption: { gallonsPerHour: 219, litersPerHour: 829 },
    emissionsFactor: { kgCO2PerKm: 2.6, kgCO2PerNauticalMile: 4.81 },
  },
  {
    id: 'gulfstream-g150',
    model: 'G150',
    manufacturer: 'Gulfstream',
    category: 'midsize',
    passengerCapacity: { typical: 6, maximum: 8 },
    range: { nauticalMiles: 3000, kilometers: 5556 },
    cruiseSpeed: { knots: 470, kmh: 870 },
    fuelConsumption: { gallonsPerHour: 240, litersPerHour: 908 },
    emissionsFactor: { kgCO2PerKm: 2.7, kgCO2PerNauticalMile: 5.00 },
  },
  {
    id: 'pilatus-pc-24',
    model: 'PC-24',
    manufacturer: 'Pilatus',
    category: 'midsize',
    passengerCapacity: { typical: 6, maximum: 8 },
    range: { nauticalMiles: 2000, kilometers: 3704 },
    cruiseSpeed: { knots: 440, kmh: 815 },
    fuelConsumption: { gallonsPerHour: 180, litersPerHour: 681 },
    emissionsFactor: { kgCO2PerKm: 2.5, kgCO2PerNauticalMile: 4.63 },
  },

  // Super Midsize Jets
  {
    id: 'bombardier-challenger-350',
    model: 'Challenger 350',
    manufacturer: 'Bombardier',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 10 },
    range: { nauticalMiles: 3200, kilometers: 5926 },
    cruiseSpeed: { knots: 470, kmh: 870 },
    fuelConsumption: { gallonsPerHour: 330, litersPerHour: 1249 },
    emissionsFactor: { kgCO2PerKm: 3.3, kgCO2PerNauticalMile: 6.11 },
  },
  {
    id: 'bombardier-challenger-3500',
    model: 'Challenger 3500',
    manufacturer: 'Bombardier',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 10 },
    range: { nauticalMiles: 3400, kilometers: 6297 },
    cruiseSpeed: { knots: 476, kmh: 882 },
    fuelConsumption: { gallonsPerHour: 267, litersPerHour: 1011 },
    emissionsFactor: { kgCO2PerKm: 3.1, kgCO2PerNauticalMile: 5.74 },
  },
  {
    id: 'cessna-citation-x-plus',
    model: 'Citation X/X+',
    manufacturer: 'Cessna',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 12 },
    range: { nauticalMiles: 3242, kilometers: 6004 },
    cruiseSpeed: { knots: 527, kmh: 976 },
    fuelConsumption: { gallonsPerHour: 348, litersPerHour: 1317 },
    emissionsFactor: { kgCO2PerKm: 3.5, kgCO2PerNauticalMile: 6.48 },
  },
  {
    id: 'cessna-citation-longitude',
    model: 'Citation Longitude',
    manufacturer: 'Cessna',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 12 },
    range: { nauticalMiles: 3500, kilometers: 6482 },
    cruiseSpeed: { knots: 483, kmh: 894 },
    fuelConsumption: { gallonsPerHour: 281, litersPerHour: 1064 },
    emissionsFactor: { kgCO2PerKm: 3.2, kgCO2PerNauticalMile: 5.93 },
  },
  {
    id: 'gulfstream-g280',
    model: 'G280',
    manufacturer: 'Gulfstream',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 10 },
    range: { nauticalMiles: 3600, kilometers: 6667 },
    cruiseSpeed: { knots: 482, kmh: 893 },
    fuelConsumption: { gallonsPerHour: 293, litersPerHour: 1109 },
    emissionsFactor: { kgCO2PerKm: 3.3, kgCO2PerNauticalMile: 6.11 },
  },
  {
    id: 'embraer-praetor-500',
    model: 'Praetor 500',
    manufacturer: 'Embraer',
    category: 'super-midsize',
    passengerCapacity: { typical: 7, maximum: 9 },
    range: { nauticalMiles: 3340, kilometers: 6186 },
    cruiseSpeed: { knots: 466, kmh: 863 },
    fuelConsumption: { gallonsPerHour: 300, litersPerHour: 1136 },
    emissionsFactor: { kgCO2PerKm: 3.2, kgCO2PerNauticalMile: 5.93 },
  },
  {
    id: 'dassault-falcon-2000lxs',
    model: 'Falcon 2000/2000EX/2000LXS',
    manufacturer: 'Dassault',
    category: 'super-midsize',
    passengerCapacity: { typical: 8, maximum: 10 },
    range: { nauticalMiles: 4000, kilometers: 7408 },
    cruiseSpeed: { knots: 482, kmh: 893 },
    fuelConsumption: { gallonsPerHour: 320, litersPerHour: 1211 },
    emissionsFactor: { kgCO2PerKm: 3.3, kgCO2PerNauticalMile: 6.11 },
  },

  // Heavy/Large Jets
  {
    id: 'bombardier-challenger-650',
    model: 'Challenger 605/650',
    manufacturer: 'Bombardier',
    category: 'heavy',
    passengerCapacity: { typical: 10, maximum: 12 },
    range: { nauticalMiles: 4000, kilometers: 7408 },
    cruiseSpeed: { knots: 470, kmh: 870 },
    fuelConsumption: { gallonsPerHour: 350, litersPerHour: 1325 },
    emissionsFactor: { kgCO2PerKm: 3.7, kgCO2PerNauticalMile: 6.85 },
  },
  {
    id: 'gulfstream-g-iv-sp',
    model: 'G-IV/G-IV-SP',
    manufacturer: 'Gulfstream',
    category: 'heavy',
    passengerCapacity: { typical: 12, maximum: 16 },
    range: { nauticalMiles: 4220, kilometers: 7815 },
    cruiseSpeed: { knots: 476, kmh: 882 },
    fuelConsumption: { gallonsPerHour: 400, litersPerHour: 1514 },
    emissionsFactor: { kgCO2PerKm: 4.1, kgCO2PerNauticalMile: 7.59 },
  },
  {
    id: 'gulfstream-g450',
    model: 'G450',
    manufacturer: 'Gulfstream',
    category: 'heavy',
    passengerCapacity: { typical: 12, maximum: 16 },
    range: { nauticalMiles: 4350, kilometers: 8056 },
    cruiseSpeed: { knots: 476, kmh: 882 },
    fuelConsumption: { gallonsPerHour: 358, litersPerHour: 1355 },
    emissionsFactor: { kgCO2PerKm: 3.9, kgCO2PerNauticalMile: 7.22 },
  },
  {
    id: 'gulfstream-g550',
    model: 'G550',
    manufacturer: 'Gulfstream',
    category: 'heavy',
    passengerCapacity: { typical: 14, maximum: 18 },
    range: { nauticalMiles: 6750, kilometers: 12501 },
    cruiseSpeed: { knots: 488, kmh: 904 },
    fuelConsumption: { gallonsPerHour: 500, litersPerHour: 1893 },
    emissionsFactor: { kgCO2PerKm: 4.8, kgCO2PerNauticalMile: 8.89 },
  },
  {
    id: 'gulfstream-g650er',
    model: 'G650/G650ER',
    manufacturer: 'Gulfstream',
    category: 'heavy',
    passengerCapacity: { typical: 13, maximum: 19 },
    range: { nauticalMiles: 7500, kilometers: 13890 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 500, litersPerHour: 1893 },
    emissionsFactor: { kgCO2PerKm: 4.8, kgCO2PerNauticalMile: 8.89 },
  },
  {
    id: 'bombardier-global-5500',
    model: 'Global 5000/5500',
    manufacturer: 'Bombardier',
    category: 'heavy',
    passengerCapacity: { typical: 13, maximum: 16 },
    range: { nauticalMiles: 5200, kilometers: 9630 },
    cruiseSpeed: { knots: 487, kmh: 902 },
    fuelConsumption: { gallonsPerHour: 478, litersPerHour: 1809 },
    emissionsFactor: { kgCO2PerKm: 4.7, kgCO2PerNauticalMile: 8.70 },
  },
  {
    id: 'bombardier-global-6500',
    model: 'Global 6000/6500',
    manufacturer: 'Bombardier',
    category: 'heavy',
    passengerCapacity: { typical: 13, maximum: 17 },
    range: { nauticalMiles: 6000, kilometers: 11112 },
    cruiseSpeed: { knots: 488, kmh: 904 },
    fuelConsumption: { gallonsPerHour: 486, litersPerHour: 1840 },
    emissionsFactor: { kgCO2PerKm: 4.8, kgCO2PerNauticalMile: 8.89 },
  },
  {
    id: 'bombardier-global-express-xrs',
    model: 'Global Express XRS',
    manufacturer: 'Bombardier',
    category: 'heavy',
    passengerCapacity: { typical: 13, maximum: 19 },
    range: { nauticalMiles: 6150, kilometers: 11390 },
    cruiseSpeed: { knots: 499, kmh: 924 },
    fuelConsumption: { gallonsPerHour: 600, litersPerHour: 2271 },
    emissionsFactor: { kgCO2PerKm: 5.5, kgCO2PerNauticalMile: 10.19 },
  },
  {
    id: 'dassault-falcon-7x',
    model: 'Falcon 7X',
    manufacturer: 'Dassault',
    category: 'heavy',
    passengerCapacity: { typical: 12, maximum: 16 },
    range: { nauticalMiles: 5950, kilometers: 11019 },
    cruiseSpeed: { knots: 488, kmh: 904 },
    fuelConsumption: { gallonsPerHour: 370, litersPerHour: 1401 },
    emissionsFactor: { kgCO2PerKm: 3.9, kgCO2PerNauticalMile: 7.22 },
  },
  {
    id: 'dassault-falcon-8x',
    model: 'Falcon 8X',
    manufacturer: 'Dassault',
    category: 'heavy',
    passengerCapacity: { typical: 12, maximum: 16 },
    range: { nauticalMiles: 6450, kilometers: 11945 },
    cruiseSpeed: { knots: 488, kmh: 904 },
    fuelConsumption: { gallonsPerHour: 350, litersPerHour: 1325 },
    emissionsFactor: { kgCO2PerKm: 3.8, kgCO2PerNauticalMile: 7.04 },
  },
  {
    id: 'embraer-legacy-650',
    model: 'Legacy 650',
    manufacturer: 'Embraer',
    category: 'heavy',
    passengerCapacity: { typical: 12, maximum: 14 },
    range: { nauticalMiles: 3900, kilometers: 7223 },
    cruiseSpeed: { knots: 464, kmh: 859 },
    fuelConsumption: { gallonsPerHour: 316, litersPerHour: 1196 },
    emissionsFactor: { kgCO2PerKm: 3.6, kgCO2PerNauticalMile: 6.67 },
  },
  {
    id: 'embraer-praetor-600',
    model: 'Praetor 600',
    manufacturer: 'Embraer',
    category: 'heavy',
    passengerCapacity: { typical: 9, maximum: 12 },
    range: { nauticalMiles: 4018, kilometers: 7441 },
    cruiseSpeed: { knots: 466, kmh: 863 },
    fuelConsumption: { gallonsPerHour: 300, litersPerHour: 1136 },
    emissionsFactor: { kgCO2PerKm: 3.2, kgCO2PerNauticalMile: 5.93 },
  },

  // Ultra-Long Range
  {
    id: 'bombardier-global-7500',
    model: 'Global 7500',
    manufacturer: 'Bombardier',
    category: 'ultra-long-range',
    passengerCapacity: { typical: 14, maximum: 19 },
    range: { nauticalMiles: 7700, kilometers: 14260 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 515, litersPerHour: 1950 },
    emissionsFactor: { kgCO2PerKm: 5.0, kgCO2PerNauticalMile: 9.26 },
  },
  {
    id: 'bombardier-global-8000',
    model: 'Global 8000',
    manufacturer: 'Bombardier',
    category: 'ultra-long-range',
    passengerCapacity: { typical: 15, maximum: 19 },
    range: { nauticalMiles: 8000, kilometers: 14816 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 525, litersPerHour: 1987 },
    emissionsFactor: { kgCO2PerKm: 5.1, kgCO2PerNauticalMile: 9.45 },
  },
  {
    id: 'gulfstream-g700',
    model: 'G700',
    manufacturer: 'Gulfstream',
    category: 'ultra-long-range',
    passengerCapacity: { typical: 13, maximum: 19 },
    range: { nauticalMiles: 7500, kilometers: 13890 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 470, litersPerHour: 1779 },
    emissionsFactor: { kgCO2PerKm: 4.7, kgCO2PerNauticalMile: 8.70 },
  },
  {
    id: 'gulfstream-g800',
    model: 'G800',
    manufacturer: 'Gulfstream',
    category: 'ultra-long-range',
    passengerCapacity: { typical: 15, maximum: 19 },
    range: { nauticalMiles: 8000, kilometers: 14816 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 490, litersPerHour: 1855 },
    emissionsFactor: { kgCO2PerKm: 4.9, kgCO2PerNauticalMile: 9.07 },
  },
  {
    id: 'dassault-falcon-10x',
    model: 'Falcon 10X',
    manufacturer: 'Dassault',
    category: 'ultra-long-range',
    passengerCapacity: { typical: 12, maximum: 19 },
    range: { nauticalMiles: 7500, kilometers: 13890 },
    cruiseSpeed: { knots: 516, kmh: 956 },
    fuelConsumption: { gallonsPerHour: 455, litersPerHour: 1722 },
    emissionsFactor: { kgCO2PerKm: 4.6, kgCO2PerNauticalMile: 8.52 },
  },
];

// Category display names
export const categoryDisplayNames: Record<Aircraft['category'], string> = {
  'turboprop': 'Turboprops',
  'very-light': 'Very Light Jets',
  'light': 'Light Jets',
  'midsize': 'Midsize Jets',
  'super-midsize': 'Super Midsize Jets',
  'heavy': 'Heavy/Large Jets',
  'ultra-long-range': 'Ultra-Long Range',
};

// Helper functions
export const getAircraftById = (id: string): Aircraft | undefined => {
  return aircraftDatabase.find(aircraft => aircraft.id === id);
};

export const getAircraftByCategory = (category: string): Aircraft[] => {
  return aircraftDatabase.filter(aircraft => aircraft.category === category);
};

export const getAllCategories = (): string[] => {
  const categories = new Set(aircraftDatabase.map(aircraft => aircraft.category));
  return Array.from(categories);
};
